# Generated by Django 5.1.7 on 2025-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_flight_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="first_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
